name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read
  packages: write

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Login to GHCR
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ghcr.io/shunya-sasaki/fastapi-rag:latest
    - name: Push the Docker image
      run: docker push ghcr.io/shunya-sasaki/fastapi-rag:latest

    - name: Trigger deploy workflow
      uses: peter-evans/repository-dispatch@v3
      with:
        token: ${{ secrets.PACKAGE_PAT }}
        repository: shunya-sasaki/docker-rag
        event-type: image-updated
        client-payload: '{"image": "ghcr.io/shunya-sasaki/rag-fastapi:latest"}'
